// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Test1() {
    driver.Navigate().GoToUrl("https://www.w3schools.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.CssSelector(".user-authenticated > .user-progress")).Click();
    {
      var element = driver.FindElement(By.LinkText("Dashboard"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.SwitchTo().Frame(0);
    driver.FindElement(By.CssSelector(".user-progress")).Click();
    driver.FindElement(By.Id("logout-link")).Click();
    driver.SwitchTo().DefaultContent();
    driver.FindElement(By.CssSelector(".LoginPanel_login__xVuiB")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".LoginPanel_social_login_button__N4C-u:nth-child(2) > .LoginPanel_provider_text__R-NWt"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".LoginPanel_login__xVuiB")).Click();
    driver.FindElement(By.CssSelector(".LoginPanel_login__xVuiB")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".LoginPanel_social_login_button__N4C-u:nth-child(3) > .LoginPanel_provider_text__R-NWt"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(1)")).SendKeys("navneetbhargava44@gmail.com");
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).SendKeys("Navneet@123");
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(3)")).SendKeys("Navneet");
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(4)")).SendKeys("Bhargava");
    {
      var element = driver.FindElement(By.CssSelector(".LoginPanel_social_login_button__N4C-u:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".CustomButton_button__V5-G\\+")).Click();
  }
}
